<?php
// Globals
const GLOBAL_IDOL_B_USED = 'idol_b_used';

// Options
const OPTION_COLLECTORS = 100;
const OPTION_COLLECTORS_A = 1;
const OPTION_COLLECTORS_RANDOM = 2;
const OPTION_COLLECTORS_B = 3;

// Collector Types
const COLLECTOR_COLLECT_PHASE = 'COLLECT_PHASE';
const COLLECTOR_END_GAME = 'END_GAME';
const COLLECTOR_ANY_TIME = 'ANY_TIME';
const COLLECTOR_BEFORE_CLAIM_PHASE = 'BEFORE_CLAIM_PHASE';

// Actions
const ACTION_CLAIM_TREASURE = "claimTreasure";
const ACTION_RECOVER_SERVANTS = "recoverServants";
const ACTION_ACTIVATE_COLLECTOR = "activateCollector";
const ACTION_END_TURN = "endTurn";

// States
const STATE_SET_UP = "gameSetup";
const STATE_SET_UP_ID = 1;

const STATE_REVEAL_TREASURE = "revealTreasure";
const STATE_REVEAL_TREASURE_ID = 10;

const STATE_BEFORE_CLAIM_PHASE = "beforeClaimPhase";
const STATE_BEFORE_CLAIM_PHASE_ID = 20;

const STATE_BEFORE_CLAIM_PHASE_ACTIVATE_COLLECTORS = "beforeClaimPhaseActivateCollectors";
const STATE_BEFORE_CLAIM_PHASE_ACTIVATE_COLLECTORS_ID = 21;

const STATE_END_BEFORE_CLAIM_PHASE_ACTIVATE_COLLECTORS = "endBeforeClaimPhaseActivateCollectors";
const STATE_END_BEFORE_CLAIM_PHASE_ACTIVATE_COLLECTORS_ID = 22;

const STATE_BEFORE_PLAYER_TURN = "beforePlayerTurn";
const STATE_BEFORE_PLAYER_TURN_ID = 30;

const STATE_PLAYER_TURN = "playerTurn";
const STATE_PLAYER_TURN_ID = 31;

const STATE_AFTER_PLAYER_TURN = "afterPlayerTurn";
const STATE_AFTER_PLAYER_TURN_ID = 32;

CONST STATE_COLLECT_TREASURE = "collectTreasure";
const STATE_COLLECT_TREASURE_ID = 40;

CONST STATE_AFTER_COLLECT_TREASURE = "afterCollectTreasure";
const STATE_AFTER_COLLECT_TREASURE_ID = 41;

CONST STATE_AFTER_COLLECT_TREASURE_ACTIVATE_COLLECTORS = "afterCollectTreasureActivateCollectors";
const STATE_AFTER_COLLECT_TREASURE_ACTIVATE_COLLECTORS_ID = 42;

CONST STATE_END_AFTER_COLLECT_TREASURE_ACTIVATE_COLLECTORS = "endAfterCollectTreasureActivateCollectors";
const STATE_END_AFTER_COLLECT_TREASURE_ACTIVATE_COLLECTORS_ID = 43;

CONST STATE_PASS_TORCH_CARDS = "passTorchCards";
const STATE_PASS_TORCH_CARDS_ID = 50;

const STATE_BEFORE_GAME_END = "beforeGameEnd";
const STATE_BEFORE_GAME_END_ID = 90;

const STATE_GAME_END = "gameEnd";
const STATE_GAME_END_ID = 99;

// Stats
const STAT_TABLE_NUMBER_OF_ROUNDS_PLAYED = "table_number_of_rounds_played";
const STAT_PLAYER_CLAIM_TREASURE_ACTION_COUNT = "player_claim_treasure_action_count";
const STAT_PLAYER_RECOVER_SERVANTS_ACTION_COUNT = "player_recover_servants_action_count";
const STAT_PLAYER_TREASURE_CARD_COUNT = "player_treasure_card_count";
const STAT_PLAYER_COLLECTOR_ACTIVATED_COUNT = "player_collector_activated_count";
